version: "3.8"

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    build:
      context: requirements/mariadb
      args:
        - MYSQL_DATABASE
        - MYSQL_ROOT
        - MYSQL_ROOT_PASSWORD
        - MYSQL_USER
        - MYSQL_PASSWORD
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - _network
    secrets:
      - secrets_env

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    build:
      context: requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress-volume:/var/www/wordpress
    networks:
      - _network
    secrets:
      - secrets_env

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    depends_on:
      - wordpress
    build: requirements/nginx
    volumes:
      - wordpress-volume:/var/www/wordpress
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf      
    networks:
      - _network
    ports:
      - 443:443

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dapaulin/data/mariadb
    
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dapaulin/data/wordpress

networks:
  _network:


secrets:
  secrets_env:
    file: .env
