version: 3.8

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      devide: /home/dapaulin/data/mariadb
    
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      devide: /home/dapaulin/data/wordpress

networks:
  back_network:

  front_network:

secrets:
  secrets_env:
    file: .env

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    build:
      context: requirements/mariadb
      args:
        - MYSQL_DATABASE
        - MYSQL_ROOT
        - MYSQL_ROOT_PASSWORD
        - MYSQL_USER
        - MYSQL_PASSWORD
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - back_network
    secrets:
      - secrets_env

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    build:
      context: requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress-volume:/var/www/wordpress
    networks:
      - back_network
      - front_network
    secrets:
      - secrets_env

  ngnix:
    container_name: ngnix
    image: ngnix
    restart: always
    depends_on:
      - wordpress
    build: requirements/ngnix
    volumes:
      
    networks:
      - front_network
    ports:
      - 443:443

  
